name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker-image.yml'
      - 'src/**'
      - 'Dockerfile'
  workflow_dispatch: {}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 检查Git代码
        uses: actions/checkout@v2

      - name: 前置DockerBuild
        uses: docker/setup-buildx-action@v1

      - name: 登录Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 构建Docker镜像
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: consistentlee/vod_hub:latest